# COURSE CONFIGURATIONS

deep_cliff:
  course_id: 1
  name: Deep Cliff
  email: admin@deepcliff.com
  f_name: Carl 
  l_name: Wheatley   
  hours: some_rnage_of_hours
  tess_slots: ["some_array_of_tee_slots","07:00","07:07"]
  
some_other_course:
  host: text-1.linkedinlabs.com
  user: cmunch
  pass: Nike2it!
  vhost: '/card'
  durable: true
  worker_threads: 1
  pending_queue_name: cardmunch.pending_queue
  trusted_pending_queue_name: cardmunch_trusted.pending_queue
  completed_queue_name: cardmunch.completed_queue
