# COURSE CONFIGURATIONS

deep_cliff:
  course_id: "one"
  name: Deep Cliff
  email: admin@deepcliff.com
  f_name: Carl 
  l_name: Wheatley   
  hours: some_rnage_of_hours
  tee_times: ["07:00", "07:07", "07:15"]
  
some_other_course:
  course_id: "one"
  name: Deep Cliff
  email: admin@deepcliff.com
  f_name: Carl 
  l_name: Wheatley   
  hours: some_rnage_of_hours
  
